app:
  name: Sample Application
  version: 2.1.0
  environment: production

database:
  host: db.example.com
  port: 5432
  name: sample_db
  pool:
    min: 5
    max: 20
    idle: 10000

features:
  authentication:
    enabled: true
    providers:
      - google
      - github
      - email
    session_timeout: 3600
  
  notifications:
    enabled: true
    channels:
      email:
        enabled: true
        provider: sendgrid
      push:
        enabled: false
        provider: null
      sms:
        enabled: true
        provider: twilio

api:
  rate_limits:
    default: 100
    authenticated: 1000
  cors:
    enabled: true
    origins:
      - https://app.example.com
      - https://admin.example.com